Algoritmo "joao03"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 12/08/2022
Var
C,F: real


Inicio
      escreval("Quantos Graus está fazendo? ")
      leia(F)
      
      C <- (F - 32)/1.8
      
      escreval(" A temperatura que está fazendo no Brasil é ",C:4:1)
 

Fimalgoritmo